import turtle

window = turtle.Screen ()
window.bgcolor ("pink")

def draw_mc():
    mc = turtle.Turtle ()
    mc.shape("turtle")
    mc.color ("black")
    mc.speed (2)
    mc.left(270)
    mc.backward (100)
    mc.left(45)
    mc.forward (50)
    mc.left(90)
    mc.forward (50)
    mc.left(45)
    mc.backward (100)
    mc.up ()
    mc.setposition (100.00,0.00)
    mc.down ()
    mc.right(10)
    mc.forward (100)
    mc.right(150)
    mc.forward (100)
    mc.up ()
    mc.setposition (110.00,40.00)
    mc.down ()
    mc.left(70)
    mc.forward (30)
    mc.up ()
    mc.setposition (250.00,0.00)
    mc.down ()
    mc.backward (75)
    mc.right(90)
    mc.backward (100)
    mc.left(90)
    mc.forward (75)

draw_mc ()


window.exitonclick ()
